import { ReactNode } from '../../../../../node_modules/.pnpm/react@19.2.7/node_modules/react';
import { ColorScheme } from '../../../types';
export type Column<T> = {
    header: string;
    key?: keyof T;
    render?: (row: T) => ReactNode;
    filterValue?: (row: T) => string;
    sortValue?: (row: T) => string | number;
    sortable?: boolean;
    className?: string;
};
export type SortDirection = 'asc' | 'desc';
export type SelectionMode = 'none' | 'single' | 'multiple';
export type Density = 'default' | 'compact';
export type DataTableProps<T> = {
    columns: Column<T>[];
    data: T[];
    keyExtractor: (row: T) => string | number;
    className?: string;
    colorScheme?: ColorScheme;
    pageSize?: number;
    searchable?: boolean;
    showPageSize?: boolean;
    searchPlaceholder?: string;
    selection?: SelectionMode;
    selected?: (string | number)[];
    onSelectionChange?: (selected: (string | number)[]) => void;
    loading?: boolean;
    density?: Density;
    stickyFirst?: boolean;
    striped?: boolean;
    scrollable?: boolean | string;
    emptyContent?: ReactNode;
    onRowClick?: (row: T) => void;
    renderExpanded?: (row: T) => ReactNode;
    expanded?: (string | number)[];
    onExpandedChange?: (expanded: (string | number)[]) => void;
};
